apiVersion: apps/v1
kind: Deployment
metadata:
  name: iit-ui-storybook
  namespace: production
  labels:
    app: iit-ui-storybook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iit-ui-storybook
  template:
    metadata:
      labels:
        app: iit-ui-storybook
    spec:
      containers:
        - name: storybook
          image: ghcr.io/apsferreira/iit-ui:sha-ba8a3db
          ports:
            - containerPort: 80
              name: http
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
      imagePullSecrets:
        - name: ghcr-secret
