apiVersion: apps/v1
kind: Deployment
metadata:
  name: storybook
  namespace: storybook
  labels:
    app: storybook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storybook
  template:
    metadata:
      labels:
        app: storybook
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 101  # nginx user
      containers:
        - name: storybook
          image: ghcr.io/apsferreira/iit-storybook:sha-8a6a2c8
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "32Mi"
              cpu: "10m"
            limits:
              memory: "64Mi"
              cpu: "100m"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 10
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
