# =============================================================================
# IngressRoute — Storybook (storybook.institutoitinerante.com.br)
# Via Traefik — roteado pelo Cloudflare Tunnel iit-prod
# =============================================================================
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: storybook
  namespace: storybook
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`storybook.institutoitinerante.com.br`)
      kind: Rule
      services:
        - name: storybook
          port: 80
