import { StoryObj } from '@storybook/react';

declare const meta: {
    title: string;
    component: import('../../../node_modules/react').ForwardRefExoticComponent<import('./Select').SelectProps & import('../../../node_modules/react').RefAttributes<HTMLSelectElement>>;
    tags: string[];
    argTypes: {
        label: {
            control: "text";
            description: string;
        };
        placeholder: {
            control: "text";
            description: string;
        };
        error: {
            control: "text";
            description: string;
        };
        helperText: {
            control: "text";
            description: string;
        };
        disabled: {
            control: "boolean";
            description: string;
            table: {
                defaultValue: {
                    summary: string;
                };
            };
        };
    };
    args: {
        options: {
            value: string;
            label: string;
        }[];
    };
    decorators: ((Story: import('@storybook/core/csf').PartialStoryFn<import('@storybook/react').ReactRenderer, {
        label?: string | undefined;
        helperText?: string | undefined;
        error?: string | undefined;
        options?: import('./Select').SelectOption[] | undefined;
        placeholder?: string | undefined;
        autoComplete?: string | undefined | undefined;
        disabled?: boolean | undefined | undefined;
        form?: string | undefined | undefined;
        multiple?: boolean | undefined | undefined;
        name?: string | undefined | undefined;
        required?: boolean | undefined | undefined;
        size?: number | undefined | undefined;
        value?: string | number | readonly string[] | undefined;
        onChange?: import('../../../node_modules/react').ChangeEventHandler<HTMLSelectElement> | undefined;
        defaultChecked?: boolean | undefined | undefined;
        defaultValue?: string | number | readonly string[] | undefined;
        suppressContentEditableWarning?: boolean | undefined | undefined;
        suppressHydrationWarning?: boolean | undefined | undefined;
        accessKey?: string | undefined | undefined;
        autoCapitalize?: "off" | "none" | "on" | "sentences" | "words" | "characters" | undefined | (string & {}) | undefined;
        autoFocus?: boolean | undefined | undefined;
        className?: string | undefined | undefined;
        contentEditable?: (boolean | "true" | "false") | "inherit" | "plaintext-only" | undefined;
        contextMenu?: string | undefined | undefined;
        dir?: string | undefined | undefined;
        draggable?: (boolean | "true" | "false") | undefined;
        enterKeyHint?: "enter" | "done" | "go" | "next" | "previous" | "search" | "send" | undefined | undefined;
        hidden?: boolean | undefined | undefined;
        id?: string | undefined | undefined;
        lang?: string | undefined | undefined;
        nonce?: string | undefined | undefined;
        slot?: string | undefined | undefined;
        spellCheck?: (boolean | "true" | "false") | undefined;
        style?: import('../../../node_modules/react').CSSProperties | undefined;
        tabIndex?: number | undefined | undefined;
        title?: string | undefined | undefined;
        translate?: "yes" | "no" | undefined | undefined;
        radioGroup?: string | undefined | undefined;
        role?: import('../../../node_modules/react').AriaRole | undefined;
        about?: string | undefined | undefined;
        content?: string | undefined | undefined;
        datatype?: string | undefined | undefined;
        inlist?: any;
        prefix?: string | undefined | undefined;
        property?: string | undefined | undefined;
        rel?: string | undefined | undefined;
        resource?: string | undefined | undefined;
        rev?: string | undefined | undefined;
        typeof?: string | undefined | undefined;
        vocab?: string | undefined | undefined;
        autoCorrect?: string | undefined | undefined;
        autoSave?: string | undefined | undefined;
        color?: string | undefined | undefined;
        itemProp?: string | undefined | undefined;
        itemScope?: boolean | undefined | undefined;
        itemType?: string | undefined | undefined;
        itemID?: string | undefined | undefined;
        itemRef?: string | undefined | undefined;
        results?: number | undefined | undefined;
        security?: string | undefined | undefined;
        unselectable?: "on" | "off" | undefined | undefined;
        inputMode?: "none" | "text" | "tel" | "url" | "email" | "numeric" | "decimal" | "search" | undefined | undefined;
        is?: string | undefined | undefined;
        exportparts?: string | undefined | undefined;
        part?: string | undefined | undefined;
        "aria-activedescendant"?: string | undefined | undefined;
        "aria-atomic"?: (boolean | "true" | "false") | undefined;
        "aria-autocomplete"?: "none" | "inline" | "list" | "both" | undefined | undefined;
        "aria-braillelabel"?: string | undefined | undefined;
        "aria-brailleroledescription"?: string | undefined | undefined;
        "aria-busy"?: (boolean | "true" | "false") | undefined;
        "aria-checked"?: boolean | "false" | "mixed" | "true" | undefined | undefined;
        "aria-colcount"?: number | undefined | undefined;
        "aria-colindex"?: number | undefined | undefined;
        "aria-colindextext"?: string | undefined | undefined;
        "aria-colspan"?: number | undefined | undefined;
        "aria-controls"?: string | undefined | undefined;
        "aria-current"?: boolean | "false" | "true" | "page" | "step" | "location" | "date" | "time" | undefined | undefined;
        "aria-describedby"?: string | undefined | undefined;
        "aria-description"?: string | undefined | undefined;
        "aria-details"?: string | undefined | undefined;
        "aria-disabled"?: (boolean | "true" | "false") | undefined;
        "aria-dropeffect"?: "none" | "copy" | "execute" | "link" | "move" | "popup" | undefined | undefined;
        "aria-errormessage"?: string | undefined | undefined;
        "aria-expanded"?: (boolean | "true" | "false") | undefined;
        "aria-flowto"?: string | undefined | undefined;
        "aria-grabbed"?: (boolean | "true" | "false") | undefined;
        "aria-haspopup"?: boolean | "false" | "true" | "menu" | "listbox" | "tree" | "grid" | "dialog" | undefined | undefined;
        "aria-hidden"?: (boolean | "true" | "false") | undefined;
        "aria-invalid"?: boolean | "false" | "true" | "grammar" | "spelling" | undefined | undefined;
        "aria-keyshortcuts"?: string | undefined | undefined;
        "aria-label"?: string | undefined | undefined;
        "aria-labelledby"?: string | undefined | undefined;
        "aria-level"?: number | undefined | undefined;
        "aria-live"?: "off" | "assertive" | "polite" | undefined | undefined;
        "aria-modal"?: (boolean | "true" | "false") | undefined;
        "aria-multiline"?: (boolean | "true" | "false") | undefined;
        "aria-multiselectable"?: (boolean | "true" | "false") | undefined;
        "aria-orientation"?: "horizontal" | "vertical" | undefined | undefined;
        "aria-owns"?: string | undefined | undefined;
        "aria-placeholder"?: string | undefined | undefined;
        "aria-posinset"?: number | undefined | undefined;
        "aria-pressed"?: boolean | "false" | "mixed" | "true" | undefined | undefined;
        "aria-readonly"?: (boolean | "true" | "false") | undefined;
        "aria-relevant"?: "additions" | "additions removals" | "additions text" | "all" | "removals" | "removals additions" | "removals text" | "text" | "text additions" | "text removals" | undefined | undefined;
        "aria-required"?: (boolean | "true" | "false") | undefined;
        "aria-roledescription"?: string | undefined | undefined;
        "aria-rowcount"?: number | undefined | undefined;
        "aria-rowindex"?: number | undefined | undefined;
        "aria-rowindextext"?: string | undefined | undefined;
        "aria-rowspan"?: number | undefined | undefined;
        "aria-selected"?: (boolean | "true" | "false") | undefined;
        "aria-setsize"?: number | undefined | undefined;
        "aria-sort"?: "none" | "ascending" | "descending" | "other" | undefined | undefined;
        "aria-valuemax"?: number | undefined | undefined;
        "aria-valuemin"?: number | undefined | undefined;
        "aria-valuenow"?: number | undefined | undefined;
        "aria-valuetext"?: string | undefined | undefined;
        children?: import('../../../node_modules/react').ReactNode;
        dangerouslySetInnerHTML?: {
            __html: string | TrustedHTML;
        } | undefined | undefined;
        onCopy?: import('../../../node_modules/react').ClipboardEventHandler<HTMLSelectElement> | undefined;
        onCopyCapture?: import('../../../node_modules/react').ClipboardEventHandler<HTMLSelectElement> | undefined;
        onCut?: import('../../../node_modules/react').ClipboardEventHandler<HTMLSelectElement> | undefined;
        onCutCapture?: import('../../../node_modules/react').ClipboardEventHandler<HTMLSelectElement> | undefined;
        onPaste?: import('../../../node_modules/react').ClipboardEventHandler<HTMLSelectElement> | undefined;
        onPasteCapture?: import('../../../node_modules/react').ClipboardEventHandler<HTMLSelectElement> | undefined;
        onCompositionEnd?: import('../../../node_modules/react').CompositionEventHandler<HTMLSelectElement> | undefined;
        onCompositionEndCapture?: import('../../../node_modules/react').CompositionEventHandler<HTMLSelectElement> | undefined;
        onCompositionStart?: import('../../../node_modules/react').CompositionEventHandler<HTMLSelectElement> | undefined;
        onCompositionStartCapture?: import('../../../node_modules/react').CompositionEventHandler<HTMLSelectElement> | undefined;
        onCompositionUpdate?: import('../../../node_modules/react').CompositionEventHandler<HTMLSelectElement> | undefined;
        onCompositionUpdateCapture?: import('../../../node_modules/react').CompositionEventHandler<HTMLSelectElement> | undefined;
        onFocus?: import('../../../node_modules/react').FocusEventHandler<HTMLSelectElement> | undefined;
        onFocusCapture?: import('../../../node_modules/react').FocusEventHandler<HTMLSelectElement> | undefined;
        onBlur?: import('../../../node_modules/react').FocusEventHandler<HTMLSelectElement> | undefined;
        onBlurCapture?: import('../../../node_modules/react').FocusEventHandler<HTMLSelectElement> | undefined;
        onChangeCapture?: import('../../../node_modules/react').FormEventHandler<HTMLSelectElement> | undefined;
        onBeforeInput?: import('../../../node_modules/react').InputEventHandler<HTMLSelectElement> | undefined;
        onBeforeInputCapture?: import('../../../node_modules/react').FormEventHandler<HTMLSelectElement> | undefined;
        onInput?: import('../../../node_modules/react').FormEventHandler<HTMLSelectElement> | undefined;
        onInputCapture?: import('../../../node_modules/react').FormEventHandler<HTMLSelectElement> | undefined;
        onReset?: import('../../../node_modules/react').FormEventHandler<HTMLSelectElement> | undefined;
        onResetCapture?: import('../../../node_modules/react').FormEventHandler<HTMLSelectElement> | undefined;
        onSubmit?: import('../../../node_modules/react').FormEventHandler<HTMLSelectElement> | undefined;
        onSubmitCapture?: import('../../../node_modules/react').FormEventHandler<HTMLSelectElement> | undefined;
        onInvalid?: import('../../../node_modules/react').FormEventHandler<HTMLSelectElement> | undefined;
        onInvalidCapture?: import('../../../node_modules/react').FormEventHandler<HTMLSelectElement> | undefined;
        onLoad?: import('../../../node_modules/react').ReactEventHandler<HTMLSelectElement> | undefined;
        onLoadCapture?: import('../../../node_modules/react').ReactEventHandler<HTMLSelectElement> | undefined;
        onError?: import('../../../node_modules/react').ReactEventHandler<HTMLSelectElement> | undefined;
        onErrorCapture?: import('../../../node_modules/react').ReactEventHandler<HTMLSelectElement> | undefined;
        onKeyDown?: import('../../../node_modules/react').KeyboardEventHandler<HTMLSelectElement> | undefined;
        onKeyDownCapture?: import('../../../node_modules/react').KeyboardEventHandler<HTMLSelectElement> | undefined;
        onKeyPress?: import('../../../node_modules/react').KeyboardEventHandler<HTMLSelectElement> | undefined;
        onKeyPressCapture?: import('../../../node_modules/react').KeyboardEventHandler<HTMLSelectElement> | undefined;
        onKeyUp?: import('../../../node_modules/react').KeyboardEventHandler<HTMLSelectElement> | undefined;
        onKeyUpCapture?: import('../../../node_modules/react').KeyboardEventHandler<HTMLSelectElement> | undefined;
        onAbort?: import('../../../node_modules/react').ReactEventHandler<HTMLSelectElement> | undefined;
        onAbortCapture?: import('../../../node_modules/react').ReactEventHandler<HTMLSelectElement> | undefined;
        onCanPlay?: import('../../../node_modules/react').ReactEventHandler<HTMLSelectElement> | undefined;
        onCanPlayCapture?: import('../../../node_modules/react').ReactEventHandler<HTMLSelectElement> | undefined;
        onCanPlayThrough?: import('../../../node_modules/react').ReactEventHandler<HTMLSelectElement> | undefined;
        onCanPlayThroughCapture?: import('../../../node_modules/react').ReactEventHandler<HTMLSelectElement> | undefined;
        onDurationChange?: import('../../../node_modules/react').ReactEventHandler<HTMLSelectElement> | undefined;
        onDurationChangeCapture?: import('../../../node_modules/react').ReactEventHandler<HTMLSelectElement> | undefined;
        onEmptied?: import('../../../node_modules/react').ReactEventHandler<HTMLSelectElement> | undefined;
        onEmptiedCapture?: import('../../../node_modules/react').ReactEventHandler<HTMLSelectElement> | undefined;
        onEncrypted?: import('../../../node_modules/react').ReactEventHandler<HTMLSelectElement> | undefined;
        onEncryptedCapture?: import('../../../node_modules/react').ReactEventHandler<HTMLSelectElement> | undefined;
        onEnded?: import('../../../node_modules/react').ReactEventHandler<HTMLSelectElement> | undefined;
        onEndedCapture?: import('../../../node_modules/react').ReactEventHandler<HTMLSelectElement> | undefined;
        onLoadedData?: import('../../../node_modules/react').ReactEventHandler<HTMLSelectElement> | undefined;
        onLoadedDataCapture?: import('../../../node_modules/react').ReactEventHandler<HTMLSelectElement> | undefined;
        onLoadedMetadata?: import('../../../node_modules/react').ReactEventHandler<HTMLSelectElement> | undefined;
        onLoadedMetadataCapture?: import('../../../node_modules/react').ReactEventHandler<HTMLSelectElement> | undefined;
        onLoadStart?: import('../../../node_modules/react').ReactEventHandler<HTMLSelectElement> | undefined;
        onLoadStartCapture?: import('../../../node_modules/react').ReactEventHandler<HTMLSelectElement> | undefined;
        onPause?: import('../../../node_modules/react').ReactEventHandler<HTMLSelectElement> | undefined;
        onPauseCapture?: import('../../../node_modules/react').ReactEventHandler<HTMLSelectElement> | undefined;
        onPlay?: import('../../../node_modules/react').ReactEventHandler<HTMLSelectElement> | undefined;
        onPlayCapture?: import('../../../node_modules/react').ReactEventHandler<HTMLSelectElement> | undefined;
        onPlaying?: import('../../../node_modules/react').ReactEventHandler<HTMLSelectElement> | undefined;
        onPlayingCapture?: import('../../../node_modules/react').ReactEventHandler<HTMLSelectElement> | undefined;
        onProgress?: import('../../../node_modules/react').ReactEventHandler<HTMLSelectElement> | undefined;
        onProgressCapture?: import('../../../node_modules/react').ReactEventHandler<HTMLSelectElement> | undefined;
        onRateChange?: import('../../../node_modules/react').ReactEventHandler<HTMLSelectElement> | undefined;
        onRateChangeCapture?: import('../../../node_modules/react').ReactEventHandler<HTMLSelectElement> | undefined;
        onSeeked?: import('../../../node_modules/react').ReactEventHandler<HTMLSelectElement> | undefined;
        onSeekedCapture?: import('../../../node_modules/react').ReactEventHandler<HTMLSelectElement> | undefined;
        onSeeking?: import('../../../node_modules/react').ReactEventHandler<HTMLSelectElement> | undefined;
        onSeekingCapture?: import('../../../node_modules/react').ReactEventHandler<HTMLSelectElement> | undefined;
        onStalled?: import('../../../node_modules/react').ReactEventHandler<HTMLSelectElement> | undefined;
        onStalledCapture?: import('../../../node_modules/react').ReactEventHandler<HTMLSelectElement> | undefined;
        onSuspend?: import('../../../node_modules/react').ReactEventHandler<HTMLSelectElement> | undefined;
        onSuspendCapture?: import('../../../node_modules/react').ReactEventHandler<HTMLSelectElement> | undefined;
        onTimeUpdate?: import('../../../node_modules/react').ReactEventHandler<HTMLSelectElement> | undefined;
        onTimeUpdateCapture?: import('../../../node_modules/react').ReactEventHandler<HTMLSelectElement> | undefined;
        onVolumeChange?: import('../../../node_modules/react').ReactEventHandler<HTMLSelectElement> | undefined;
        onVolumeChangeCapture?: import('../../../node_modules/react').ReactEventHandler<HTMLSelectElement> | undefined;
        onWaiting?: import('../../../node_modules/react').ReactEventHandler<HTMLSelectElement> | undefined;
        onWaitingCapture?: import('../../../node_modules/react').ReactEventHandler<HTMLSelectElement> | undefined;
        onAuxClick?: import('../../../node_modules/react').MouseEventHandler<HTMLSelectElement> | undefined;
        onAuxClickCapture?: import('../../../node_modules/react').MouseEventHandler<HTMLSelectElement> | undefined;
        onClick?: import('../../../node_modules/react').MouseEventHandler<HTMLSelectElement> | undefined;
        onClickCapture?: import('../../../node_modules/react').MouseEventHandler<HTMLSelectElement> | undefined;
        onContextMenu?: import('../../../node_modules/react').MouseEventHandler<HTMLSelectElement> | undefined;
        onContextMenuCapture?: import('../../../node_modules/react').MouseEventHandler<HTMLSelectElement> | undefined;
        onDoubleClick?: import('../../../node_modules/react').MouseEventHandler<HTMLSelectElement> | undefined;
        onDoubleClickCapture?: import('../../../node_modules/react').MouseEventHandler<HTMLSelectElement> | undefined;
        onDrag?: import('../../../node_modules/react').DragEventHandler<HTMLSelectElement> | undefined;
        onDragCapture?: import('../../../node_modules/react').DragEventHandler<HTMLSelectElement> | undefined;
        onDragEnd?: import('../../../node_modules/react').DragEventHandler<HTMLSelectElement> | undefined;
        onDragEndCapture?: import('../../../node_modules/react').DragEventHandler<HTMLSelectElement> | undefined;
        onDragEnter?: import('../../../node_modules/react').DragEventHandler<HTMLSelectElement> | undefined;
        onDragEnterCapture?: import('../../../node_modules/react').DragEventHandler<HTMLSelectElement> | undefined;
        onDragExit?: import('../../../node_modules/react').DragEventHandler<HTMLSelectElement> | undefined;
        onDragExitCapture?: import('../../../node_modules/react').DragEventHandler<HTMLSelectElement> | undefined;
        onDragLeave?: import('../../../node_modules/react').DragEventHandler<HTMLSelectElement> | undefined;
        onDragLeaveCapture?: import('../../../node_modules/react').DragEventHandler<HTMLSelectElement> | undefined;
        onDragOver?: import('../../../node_modules/react').DragEventHandler<HTMLSelectElement> | undefined;
        onDragOverCapture?: import('../../../node_modules/react').DragEventHandler<HTMLSelectElement> | undefined;
        onDragStart?: import('../../../node_modules/react').DragEventHandler<HTMLSelectElement> | undefined;
        onDragStartCapture?: import('../../../node_modules/react').DragEventHandler<HTMLSelectElement> | undefined;
        onDrop?: import('../../../node_modules/react').DragEventHandler<HTMLSelectElement> | undefined;
        onDropCapture?: import('../../../node_modules/react').DragEventHandler<HTMLSelectElement> | undefined;
        onMouseDown?: import('../../../node_modules/react').MouseEventHandler<HTMLSelectElement> | undefined;
        onMouseDownCapture?: import('../../../node_modules/react').MouseEventHandler<HTMLSelectElement> | undefined;
        onMouseEnter?: import('../../../node_modules/react').MouseEventHandler<HTMLSelectElement> | undefined;
        onMouseLeave?: import('../../../node_modules/react').MouseEventHandler<HTMLSelectElement> | undefined;
        onMouseMove?: import('../../../node_modules/react').MouseEventHandler<HTMLSelectElement> | undefined;
        onMouseMoveCapture?: import('../../../node_modules/react').MouseEventHandler<HTMLSelectElement> | undefined;
        onMouseOut?: import('../../../node_modules/react').MouseEventHandler<HTMLSelectElement> | undefined;
        onMouseOutCapture?: import('../../../node_modules/react').MouseEventHandler<HTMLSelectElement> | undefined;
        onMouseOver?: import('../../../node_modules/react').MouseEventHandler<HTMLSelectElement> | undefined;
        onMouseOverCapture?: import('../../../node_modules/react').MouseEventHandler<HTMLSelectElement> | undefined;
        onMouseUp?: import('../../../node_modules/react').MouseEventHandler<HTMLSelectElement> | undefined;
        onMouseUpCapture?: import('../../../node_modules/react').MouseEventHandler<HTMLSelectElement> | undefined;
        onSelect?: import('../../../node_modules/react').ReactEventHandler<HTMLSelectElement> | undefined;
        onSelectCapture?: import('../../../node_modules/react').ReactEventHandler<HTMLSelectElement> | undefined;
        onTouchCancel?: import('../../../node_modules/react').TouchEventHandler<HTMLSelectElement> | undefined;
        onTouchCancelCapture?: import('../../../node_modules/react').TouchEventHandler<HTMLSelectElement> | undefined;
        onTouchEnd?: import('../../../node_modules/react').TouchEventHandler<HTMLSelectElement> | undefined;
        onTouchEndCapture?: import('../../../node_modules/react').TouchEventHandler<HTMLSelectElement> | undefined;
        onTouchMove?: import('../../../node_modules/react').TouchEventHandler<HTMLSelectElement> | undefined;
        onTouchMoveCapture?: import('../../../node_modules/react').TouchEventHandler<HTMLSelectElement> | undefined;
        onTouchStart?: import('../../../node_modules/react').TouchEventHandler<HTMLSelectElement> | undefined;
        onTouchStartCapture?: import('../../../node_modules/react').TouchEventHandler<HTMLSelectElement> | undefined;
        onPointerDown?: import('../../../node_modules/react').PointerEventHandler<HTMLSelectElement> | undefined;
        onPointerDownCapture?: import('../../../node_modules/react').PointerEventHandler<HTMLSelectElement> | undefined;
        onPointerMove?: import('../../../node_modules/react').PointerEventHandler<HTMLSelectElement> | undefined;
        onPointerMoveCapture?: import('../../../node_modules/react').PointerEventHandler<HTMLSelectElement> | undefined;
        onPointerUp?: import('../../../node_modules/react').PointerEventHandler<HTMLSelectElement> | undefined;
        onPointerUpCapture?: import('../../../node_modules/react').PointerEventHandler<HTMLSelectElement> | undefined;
        onPointerCancel?: import('../../../node_modules/react').PointerEventHandler<HTMLSelectElement> | undefined;
        onPointerCancelCapture?: import('../../../node_modules/react').PointerEventHandler<HTMLSelectElement> | undefined;
        onPointerEnter?: import('../../../node_modules/react').PointerEventHandler<HTMLSelectElement> | undefined;
        onPointerLeave?: import('../../../node_modules/react').PointerEventHandler<HTMLSelectElement> | undefined;
        onPointerOver?: import('../../../node_modules/react').PointerEventHandler<HTMLSelectElement> | undefined;
        onPointerOverCapture?: import('../../../node_modules/react').PointerEventHandler<HTMLSelectElement> | undefined;
        onPointerOut?: import('../../../node_modules/react').PointerEventHandler<HTMLSelectElement> | undefined;
        onPointerOutCapture?: import('../../../node_modules/react').PointerEventHandler<HTMLSelectElement> | undefined;
        onGotPointerCapture?: import('../../../node_modules/react').PointerEventHandler<HTMLSelectElement> | undefined;
        onGotPointerCaptureCapture?: import('../../../node_modules/react').PointerEventHandler<HTMLSelectElement> | undefined;
        onLostPointerCapture?: import('../../../node_modules/react').PointerEventHandler<HTMLSelectElement> | undefined;
        onLostPointerCaptureCapture?: import('../../../node_modules/react').PointerEventHandler<HTMLSelectElement> | undefined;
        onScroll?: import('../../../node_modules/react').UIEventHandler<HTMLSelectElement> | undefined;
        onScrollCapture?: import('../../../node_modules/react').UIEventHandler<HTMLSelectElement> | undefined;
        onWheel?: import('../../../node_modules/react').WheelEventHandler<HTMLSelectElement> | undefined;
        onWheelCapture?: import('../../../node_modules/react').WheelEventHandler<HTMLSelectElement> | undefined;
        onAnimationStart?: import('../../../node_modules/react').AnimationEventHandler<HTMLSelectElement> | undefined;
        onAnimationStartCapture?: import('../../../node_modules/react').AnimationEventHandler<HTMLSelectElement> | undefined;
        onAnimationEnd?: import('../../../node_modules/react').AnimationEventHandler<HTMLSelectElement> | undefined;
        onAnimationEndCapture?: import('../../../node_modules/react').AnimationEventHandler<HTMLSelectElement> | undefined;
        onAnimationIteration?: import('../../../node_modules/react').AnimationEventHandler<HTMLSelectElement> | undefined;
        onAnimationIterationCapture?: import('../../../node_modules/react').AnimationEventHandler<HTMLSelectElement> | undefined;
        onTransitionEnd?: import('../../../node_modules/react').TransitionEventHandler<HTMLSelectElement> | undefined;
        onTransitionEndCapture?: import('../../../node_modules/react').TransitionEventHandler<HTMLSelectElement> | undefined;
        ref?: import('../../../node_modules/react').LegacyRef<HTMLSelectElement> | undefined;
        key?: import('../../../node_modules/react').Key | null | undefined;
    }>) => import("react/jsx-runtime").JSX.Element)[];
};
export default meta;
type Story = StoryObj<typeof meta>;
export declare const Default: Story;
export declare const WithLabel: Story;
export declare const WithError: Story;
export declare const Disabled: Story;
export declare const WithManyOptions: Story;
